FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.11 AS builder
WORKDIR /src/ovirt-csi-driver
COPY . .
RUN make build

FROM registry.ci.openshift.org/ocp/4.11:base

RUN yum install -y e2fsprogs xfsprogs
COPY --from=builder /src/ovirt-csi-driver/bin/ovirt-csi-driver .

ENTRYPOINT ["./ovirt-csi-driver"]
